<?xml version="1.0" encoding="utf-8"?><Database Name="FamilyWizard" Class="FamilyWizardDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SBYRD-DELL\SQLEXPRESS;Initial Catalog=FamilyWizard;Integrated Security=True" SettingsObjectName="FamilyWizard.My.MySettings" SettingsPropertyName="FamilyWizardConnectionString" Provider="System.Data.SqlClient" />
</Database>